More cleanup and support for concrete as part of a project hierarchy.
GayPizzaSpecifications/concrete pull request #2
Opened 2022-07-10 22:18 UTC by kendfinger

2022-07-10 22:19 UTC, kendfinger commented
I would recommend not releasing after this as I have a few more changes I want to make.

2022-07-10 23:41 UTC, kendfinger commented
This should be ready to merge, it adds a library concept so that you can have libraries where the bukkit API is accessible but doesn't get counted as a plugin. Also added is a GitHub workflow for making sure the plugin builds.

2022-07-12 07:19 UTC, lgorence requested changes
There are some quick changes I'd like addressed, but the rest looks good. I'll rereview once they're made.

2022-07-12 07:19 UTC, lgorence commented on samples/mixed/bukkit-plugins/common-library/src/main/kotlin/lgbt/mystic/foundation/conrete/sample/common/CommonExtensions.kt
> +package lgbt.mystic.foundation.conrete.sample.common
`conrete`

2022-07-12 07:19 UTC, lgorence commented on samples/simple/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Could this be bumped to 7.4.2 please?

2022-07-12 07:19 UTC, lgorence commented on src/main/kotlin/lgbt/mystic/foundation/concrete/extensions.kt
>  package lgbt.mystic.foundation.concrete
Could you please add a bit of documentation to this class?

2022-07-12 07:19 UTC, lgorence commented on src/main/kotlin/lgbt/mystic/foundation/concrete/extensions.kt
>  package lgbt.mystic.foundation.concrete
Or file, rather.

2022-07-12 07:29 UTC, lgorence commented
Looks good, thanks.

2022-07-12 07:29 UTC, merged